# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    - sphinx-build -b html -D language='en' docs/source $READTHEDOCS_OUTPUT/html/en
    - sphinx-build -b html -D language='es' docs/source $READTHEDOCS_OUTPUT/html/es

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
    - requirements: requirements.txt