services:
  nettracker-db:
    container_name: net-tracker-db
    image: mongo
    ports:
      - "27017:27017"
    network_mode: host
    profiles: [db]

  nettracker-api:
    container_name: net-tracker-api
    build: .
    network_mode: host